### ISSUE TITLE
Support LLVM Clang 7.0 and C++17

### ISSUE THREAD

**Issue by Jerry-Ma** [arcosuc3m/grppi#365]
Hi,

I am trying to build a data processing pipeline in C++, and this library looks very promising to me and I would like to give it a try. 

I tried to compile with C++17 on a macOS 10.14 and have not yet succeeded.

The main issue is that in C++17 experimental::optional is merge to the std namespace.

I therefore went on and cleaned up the code, added linker flags `c++experimental` as required by the my llvm clang 7.0 compiler installed via `brew install llvm`, but still, the unit-tests won't build due to the following error:

```
In file included from /Users/ma/Codes/devs/grppi/unit_tests/context.cpp:22:
In file included from /Users/ma/Codes/devs/grppi/include/grppi.h:20:
In file included from /Users/ma/Codes/devs/grppi/include/dyn/dynamic_execution.h:21:
In file included from /Users/ma/Codes/devs/grppi/include/tbb/parallel_execution_tbb.h:30:
In file included from /usr/local/include/tbb/tbb.h:72:
/usr/local/include/tbb/pipeline.h:394:30: error: call to implicitly-deleted
      default constructor of
      'tbb::interface6::internal::token_helper<std::__1::optional<int>,
      false>::type_to_void_ptr_map'
        type_to_void_ptr_map mymap;
                             ^
/usr/local/include/tbb/pipeline.h:446:26: note: in instantiation of member
      function 'tbb::interface6::internal::token_helper<std::__1::optional<int>,
      false>::cast_to_void_ptr' requested here
        return u_helper::cast_to_void_ptr(output_u);
                         ^

... (much more similar)
```

It seems to me that this is due to some incompatibility between C++17 and intel TBB (version 2019_U3), but nothing relevant could be found from googling TBB + C++17.

So I just wanted to ask if you have any insight of getting it compiled. Thank you very much!

**Comment by jdgarciauc3m** [comment]
Solved by issue #369.
